# This is a basic workflow to help you get started with Actions

name: JS Actions

# Controls when the workflow will run
on: [push]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel other commit
jobs:
  action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      
      - name: hello-action
        uses: ./.github/actions/hello-world
        with:
          first-greeting: "Learning Lab User"
